version: '3.8'
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-c
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        image: dev1800/node-app
        depends_on:
            - database
            - redis
    database:
        container_name: database-c
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=skdev
            - MONGO_INITDB_ROOT_PASSWORD=skdev
        volumes:
            - mongo-db:/data/db
    redis:
        container_name: redis-c
        image: redis

volumes:
    mongo-db:
