version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-cc:
    build: .
    image: dev1800/node-cc
    env_file:
      - ./.env
    depends_on:
      - database
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=skdev
      - MONGO_INITDB_ROOT_PASSWORD=skdev
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
