version: "3.8"
services:
  nginx:
    ports:
      - "80:80"
  node-cc:
    build:
      context: .
      args: 
        NODE_ENV: production
    env_file:
      - ./.env.production
    command: node index.js