version: "3.8"
services:
  nginx:
    ports:
      - "5000:80"
  node-cc:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.development
    command: yarn dev
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=skdev
      - MONGO_INITDB_ROOT_PASSWORD=skdev
      