version: '3.8'
services:
    nginx:
        ports:
            - '80:80'
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        # Docker Swarm configurations
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 2
                delay: 15s

        environment:
            - NODE_ENV=production
            - MONGO_USERNAME=skdev
            - MONGO_PASSWORD=skdev
            - SESSION_SECRET=sessionsecret
            - MONGO_IP_ADDRESS=database
            - MONGO_PORT=27017
        command: node index.js
        ports:
            - '5000:5000'
    database:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=skdev
            - MONGO_INITDB_ROOT_PASSWORD=skdev
